import { MINUS_TIME_VALUE } from '../global.js';
import { KEY_ALIAS } from '../types.js';

export const SK_AIRFLYPROV3: KEY_ALIAS[] = [
  //SECTION PRESET
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset1',
    code: '1',
    type: 'B4',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset2',
    code: '2',
    type: 'B4',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset3',
    code: '3',
    type: 'B4',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset4',
    code: '4',
    type: 'B4',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset5',
    code: '5',
    type: 'B4',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset6',
    code: '6',
    type: 'B4',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset7',
    code: '7',
    type: 'B4',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset8',
    code: '8',
    type: 'B4',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset9',
    code: '9',
    type: 'B4',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset10',
    code: '10',
    type: 'B4',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset11',
    code: '11',
    type: 'B4',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset12',
    code: '12',
    type: 'B4',
    group: 'preset',
  },
  //SECTION PROGRAM
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program1',
    code: '13',
    type: 'B4',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program2',
    code: '14',
    type: 'B4',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program3',
    code: '15',
    type: 'B4',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program4',
    code: '16',
    type: 'B4',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program5',
    code: '17',
    type: 'B4',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program6',
    code: '18',
    type: 'B4',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program7',
    code: '19',
    type: 'B4',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program8',
    code: '20',
    type: 'B4',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program9',
    code: '21',
    type: 'B4',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program10',
    code: '22',
    type: 'B4',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program11',
    code: '23',
    type: 'B4',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program12',
    code: '24',
    type: 'B4',
    group: 'program',
  },
  //SECTION TBAR
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'TbarDisplay',
    code: '49',
    type: 'D',
    group: 'slider_display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'TBar',
    code: '50',
    type: 'Tbar',
    group: 'slider',
  },
  //SECTION ACTION BUTTONS
  { time: MINUS_TIME_VALUE, isPressed: false, alias: 'CUT', code: '51', type: 'B4', group: 'cut' },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'AUTO',
    code: '52',
    type: 'B4',
    group: 'auto',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'FTB',
    code: '53',
    type: 'B4',
    group: 'stay_blinking',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'SHIFT',
    code: '54',
    type: 'B4',
    group: 'shift',
  },
  //SECTION MIXER
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer0',
    code: '63',
    type: 'B4',
    group: 'mixer',
  }, //KEY1
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer1',
    code: '64',
    type: 'B4',
    group: 'mixer',
  }, //KEY2
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer2',
    code: '65',
    type: 'B4',
    group: 'mixer',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer3',
    code: '66',
    type: 'B4',
    group: 'mixer',
  },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Mixer4',
  //   code: '61',
  //   type: 'B4',
  //   group: 'mixer',
  // },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Mixer5',
  //   code: '62',
  //   type: 'B4',
  //   group: 'mixer',
  // },
  //SECTION KEYER
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Keyer0',
  //   code: '63',
  //   type: 'B4',
  //   group: 'keyer',
  // },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Keyer1',
  //   code: '64',
  //   type: 'B4',
  //   group: 'keyer',
  // },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Keyer2',
  //   code: '65',
  //   type: 'B4',
  //   group: 'keyer',
  // },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Keyer3',
  //   code: '66',
  //   type: 'B4',
  //   group: 'keyer',
  // },
  //SECTION Display
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'StatusDisplay',
    code: '37',
    type: 'D',
    group: 'vm_display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'MeDisplay',
    code: '69',
    type: 'D',
    group: 'me_display',
  },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'StatusDisplay',
  //   code: '69',
  //   type: 'D',
  //   group: 'vm_display',
  // },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'MeDisplay',
  //   code: '56',
  //   type: 'D',
  //   group: 'me_display',
  // },
  //SECTION ENCODERS
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'CLIP',
    code: '85',
    type: 'Enc',
    group: 'encoder',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'GAIN',
    code: '86',
    type: 'Enc',
    group: 'encoder',
  },
  //SECTION ROUTE_IN
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'In0',
    code: '38',
    type: 'B4',
    group: 'route_in',
  },

  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'In1',
    code: '39',
    type: 'B4',
    group: 'route_in',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'In2',
    code: '40',
    type: 'B4',
    group: 'route_in',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'In3',
    code: '41',
    type: 'B4',
    group: 'route_in',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'In4',
    code: '42',
    type: 'B4',
    group: 'route_in',
  },
  //SECTION ROUTE OUT
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out0',
    code: '57',
    type: 'B4',
    group: 'route_out',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out1',
    code: '58',
    type: 'B4',
    group: 'route_out',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out2',
    code: '59',
    type: 'B4',
    group: 'route_out',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out3',
    code: '60',
    type: 'B4',
    group: 'route_out',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out4',
    code: '61',
    type: 'B4',
    group: 'route_out',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out5',
    code: '62',
    type: 'B4',
    group: 'route_out',
  },
];
