// import { MINUS_TIME_VALUE } from '../constants.js';
import { MINUS_TIME_VALUE } from '../global.js';
import { KEY_ALIAS } from '../types.js';

export const SK_MASTERKEYONE: KEY_ALIAS[] = [
  //SECTION XBAR display
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay1',
    code: '43',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay2',
    code: '44',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay3',
    code: '45',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay4',
    code: '46',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay5',
    code: '47',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay6',
    code: '48',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay7',
    code: '49',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay8',
    code: '50',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay9',
    code: '51',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay10',
    code: '52',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay11',
    code: '53',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'XbarDisplay12',
    code: '54',
    type: 'D',
    group: 'display',
  },
  //SECTION PRESET
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset1',
    code: '1',
    type: 'B',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset2',
    code: '2',
    type: 'B',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset3',
    code: '3',
    type: 'B',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset4',
    code: '4',
    type: 'B',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset5',
    code: '5',
    type: 'B',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset6',
    code: '6',
    type: 'B',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset7',
    code: '7',
    type: 'B',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset8',
    code: '8',
    type: 'B',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset9',
    code: '9',
    type: 'B',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset10',
    code: '10',
    type: 'B',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset11',
    code: '11',
    type: 'B',
    group: 'preset',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Preset12',
    code: '12',
    type: 'B',
    group: 'preset',
  },
  //SECTION PROGRAM
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program1',
    code: '13',
    type: 'B',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program2',
    code: '14',
    type: 'B',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program3',
    code: '15',
    type: 'B',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program4',
    code: '16',
    type: 'B',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program5',
    code: '17',
    type: 'B',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program6',
    code: '18',
    type: 'B',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program7',
    code: '19',
    type: 'B',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program8',
    code: '20',
    type: 'B',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program9',
    code: '21',
    type: 'B',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program10',
    code: '22',
    type: 'B',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program11',
    code: '23',
    type: 'B',
    group: 'program',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Program12',
    code: '24',
    type: 'B',
    group: 'program',
  },
  //SECTION KEYER
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Keyer0',
  //   code: '36',
  //   type: 'B',
  //   group: 'keyer',
  // },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Keyer1',
  //   code: '37',
  //   type: 'B',
  //   group: 'keyer',
  // },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Keyer2',
  //   code: '38',
  //   type: 'B',
  //   group: 'keyer',
  // },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Keyer3',
  //   code: '39',
  //   type: 'B',
  //   group: 'keyer',
  // },
  //SECTION TBAR
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'TbarDisplay',
    code: '93',
    type: 'D',
    group: 'slider_display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'TBar',
    code: '94',
    type: 'Tbar',
    group: 'slider',
  },
  //SECTION ACTION BUTTONS
  { time: MINUS_TIME_VALUE, isPressed: false, alias: 'CUT', code: '55', type: 'B', group: 'cut' },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'AUTO',
    code: '56',
    type: 'B',
    group: 'auto',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'FTB',
    code: '57',
    type: 'B',
    group: 'ftb',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Shift',
    code: '58',
    type: 'B',
    group: 'shift',
  },
  //SECTION ENCODER
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'CLIP',
    code: '111',
    type: 'Enc',
    group: 'encoder',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'GAIN',
    code: '112',
    type: 'Enc',
    group: 'encoder',
  },
  //SECTION MIXER
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer0',
    code: '59',
    type: 'B',
    group: 'mixer',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer1',
    code: '60',
    type: 'B',
    group: 'mixer',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer2',
    code: '61',
    type: 'B',
    group: 'mixer',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer3',
    code: '62',
    type: 'B',
    group: 'mixer',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer0Display',
    code: '69',
    type: 'D',
    group: 'display',
  },

  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer1Display',
    code: '70',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer2Display',
    code: '71',
    type: 'D',
    group: 'display',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Mixer3Display',
    code: '72',
    type: 'D',
    group: 'display',
  },
  //SECTION display
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'StatusDisplay',
    code: '95',
    type: 'D',
    group: 'vm_display',
  },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'StatusDisplay',
  //   code: '88',
  //   type: 'D',
  //   group: 'vm_display',
  // },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'MeDisplay',
    code: '88',
    type: 'D',
    group: 'me_display',
  },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Mixer4',
  //   code: '119',
  //   type: 'B4',
  //   group: 'mixer',
  // },
  // {
  //   time: MINUS_TIME_VALUE,
  //   isPressed: false,
  //   alias: 'Mixer5',
  //   code: '120',
  //   type: 'B4',
  //   group: 'mixer',
  // },
  //SECTION ROUTE_IN
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'In0',
    code: '99',
    type: 'B4',
    group: 'route_in',
  },

  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'In1',
    code: '100',
    type: 'B4',
    group: 'route_in',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'In2',
    code: '101',
    type: 'B4',
    group: 'route_in',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'In3',
    code: '102',
    type: 'B4',
    group: 'route_in',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'In4',
    code: '103',
    type: 'B4',
    group: 'route_in',
  },
  //SECTION ROUTE OUT
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out0',
    code: '115',
    type: 'B4',
    group: 'route_out',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out1',
    code: '116',
    type: 'B4',
    group: 'route_out',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out2',
    code: '117',
    type: 'B4',
    group: 'route_out',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out3',
    code: '118',
    type: 'B4',
    group: 'route_out',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out4',
    code: '119',
    type: 'B4',
    group: 'route_out',
  },
  {
    time: MINUS_TIME_VALUE,
    isPressed: false,
    alias: 'Out5',
    code: '120',
    type: 'B4',
    group: 'route_out',
  },
];
